#!/usr/bin/env bash
# Run Terraform inside a container, against the lab emulator.
#
# For machines where endpoint security intercepts the loopback mTLS handshake
# between Terraform and its provider plugins, which fails as:
#
#   Failed to load plugin schemas ... Plugin did not respond
#   transport: authentication handshake failed: tls: ... signed by unknown authority
#
# Inside a container that handshake happens in its own network namespace, where
# the host's filter driver never sees it. Nothing is disabled and no TLS is
# weakened. See labs/README.md for how to tell this failure apart from a slow
# emulator.
#
# Run it from a lab directory, exactly where you would have run tflocal:
#
#     "$(git rev-parse --show-toplevel)/labs/tf-docker.sh" init
#     "$(git rev-parse --show-toplevel)/labs/tf-docker.sh" apply -auto-approve
#     "$(git rev-parse --show-toplevel)/labs/tf-docker.sh" destroy -auto-approve
#
# Overridable with environment variables: TF_IMAGE, EMULATOR_CONTAINER,
# PLUGIN_VOLUME.
set -euo pipefail

TF_IMAGE="${TF_IMAGE:-hashicorp/terraform:1.15.8}"
EMULATOR_CONTAINER="${EMULATOR_CONTAINER:-floci-lab}"
PLUGIN_VOLUME="${PLUGIN_VOLUME:-tf-plugins}"
OVERRIDE_FILE="docker_providers_override.tf"

if [ "$#" -eq 0 ]; then
  echo "usage: tf-docker.sh <terraform arguments...>" >&2
  exit 64
fi

# The emulator's Docker network, so the container resolves it by name rather
# than going back out through the host.
network="$(docker inspect -f '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{end}}' \
  "$EMULATOR_CONTAINER" 2>/dev/null || true)"

if [ -z "$network" ]; then
  echo "Emulator container '$EMULATOR_CONTAINER' is not running." >&2
  echo "Start it with: docker compose -f labs/docker-compose.yml up -d" >&2
  exit 1
fi

# Terraform merges *_override.tf over the lab's own provider block, which is
# how the lab's .tf files stay untouched and still apply to real AWS. Rewritten
# every run so a stale endpoint can never survive. Gitignored via *_override.tf.
endpoint="http://${EMULATOR_CONTAINER}:4566"
cat > "$OVERRIDE_FILE" <<EOF
# Generated by labs/tf-docker.sh. Safe to delete. Do not edit.
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true

  endpoints {
    s3        = "${endpoint}"
    s3control = "${endpoint}"
    sts       = "${endpoint}"
    iam       = "${endpoint}"
  }
}
EOF

# Git Bash reports POSIX paths that the Docker daemon cannot resolve, and
# rewrites arguments that look like paths unless MSYS_NO_PATHCONV is set.
host_pwd="$(pwd -W 2>/dev/null || pwd)"

MSYS_NO_PATHCONV=1 docker run --rm -i \
  -v "${host_pwd}:/work" \
  -w /work \
  -v "${PLUGIN_VOLUME}:/plugins" \
  -e TF_PLUGIN_CACHE_DIR=/plugins \
  --network "$network" \
  "$TF_IMAGE" "$@"
