# Run Terraform inside a container, against the lab emulator.
#
# For machines where endpoint security intercepts the loopback mTLS handshake
# between Terraform and its provider plugins, which fails as:
#
#   Failed to load plugin schemas ... Plugin did not respond
#   transport: authentication handshake failed: tls: ... signed by unknown authority
#
# Inside a container that handshake happens in its own network namespace, where
# the host's filter driver never sees it. Nothing is disabled and no TLS is
# weakened. See labs/README.md for how to tell this failure apart from a slow
# emulator.
#
# Run it from a lab directory, exactly where you would have run tflocal:
#
#     & "$(git rev-parse --show-toplevel)/labs/tf-docker.ps1" init
#     & "$(git rev-parse --show-toplevel)/labs/tf-docker.ps1" apply -auto-approve
#     & "$(git rev-parse --show-toplevel)/labs/tf-docker.ps1" destroy -auto-approve
#
# Overridable with environment variables: TF_IMAGE, EMULATOR_CONTAINER,
# PLUGIN_VOLUME.

[CmdletBinding()]
param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]] $TerraformArgs
)

$ErrorActionPreference = "Stop"

$image     = if ($env:TF_IMAGE) { $env:TF_IMAGE } else { "hashicorp/terraform:1.15.8" }
$emulator  = if ($env:EMULATOR_CONTAINER) { $env:EMULATOR_CONTAINER } else { "floci-lab" }
$volume    = if ($env:PLUGIN_VOLUME) { $env:PLUGIN_VOLUME } else { "tf-plugins" }
$overrideFile = "docker_providers_override.tf"

if (-not $TerraformArgs -or $TerraformArgs.Count -eq 0) {
    Write-Host "usage: tf-docker.ps1 <terraform arguments...>"
    exit 64
}

# The emulator's Docker network, so the container resolves it by name rather
# than going back out through the host.
$template = '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{end}}'
$network = docker inspect -f $template $emulator 2>$null

if (-not $network) {
    Write-Error "Emulator container '$emulator' is not running. Start it with: docker compose -f labs/docker-compose.yml up -d"
    exit 1
}

# Terraform merges *_override.tf over the lab's own provider block, which is
# how the lab's .tf files stay untouched and still apply to real AWS. Rewritten
# every run so a stale endpoint can never survive. Gitignored via *_override.tf.
$endpoint = "http://${emulator}:4566"
@"
# Generated by labs/tf-docker.ps1. Safe to delete. Do not edit.
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true

  endpoints {
    s3        = "$endpoint"
    s3control = "$endpoint"
    sts       = "$endpoint"
    iam       = "$endpoint"
  }
}
"@ | Set-Content -Path $overrideFile

docker run --rm -i `
    -v "$($PWD.Path):/work" `
    -w /work `
    -v "${volume}:/plugins" `
    -e TF_PLUGIN_CACHE_DIR=/plugins `
    --network $network `
    $image @TerraformArgs

exit $LASTEXITCODE
